YouriPortfolio/YouriPortfolio/Models/ViewModels/ProjectViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace YouriPortfolio.Models.ViewModels
{
    public class ProjectViewModel
    {
        public ProjectViewModel()
        {
            Project = new Content();
        }
        public Content Project { get; set; }
        public string PostVideo { get; set; }
        public string DeleteConfirmationName { get; set; }
    }
}

YouriPortfolio/YouriPortfolio/Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using PCAuthLib;
using PermacallWebApp.Repos;
using YouriPortfolio.Logic;
using YouriPortfolio.Models;
using YouriPortfolio.Models.ViewModels;
using YouriPortfolio.Repos;

namespace YouriPortfolio.Controllers
{
    public class ProjectsController : Controller
    {
        // GET: Project
        public ActionResult Index()
        {
            if (!Login.ForceHTTPSConnection(System.Web.HttpContext.Current, true)) return new EmptyResult();
            LogRepo.Log(System.Web.HttpContext.Current);
            var currentUser = Login.GetCurrentUser(System.Web.HttpContext.Current);

            ProjectListViewModel viewModel = new ProjectListViewModel();

            List<Content> content =
                ContentRepo.GetAllContent(isAdmin: currentUser.Permission == PCAuthLib.User.PermissionGroup.ADMIN);

            if (content != null)
            {
                foreach (Content contentItem in content)
                {
                    BBCode.ParseContent(contentItem);

                    contentItem.HeaderImg = VisualsRepo.RandomVisual(contentItem.ID);
                }
            }

            viewModel.ContentList = content ?? new List<Content>();

            return View(viewModel);
        }
        // GET: Project/[ID]
        public ActionResult Get(int ID = 0)
        {
            if (!Login.ForceHTTPSConnection(System.Web.HttpContext.Current, true)) return new EmptyResult();
            LogRepo.Log(System.Web.HttpContext.Current);
            var currentUser = Login.GetCurrentUser(System.Web.HttpContext.Current);

            ProjectViewModel viewModel = new ProjectViewModel();
            if (ID < 0) ID = ID * -1;
            Content content = ContentRepo.GetContent(ID, currentUser.Permission == PCAuthLib.User.PermissionGroup.ADMIN);

            if (content == null) return RedirectToAction("Index");

            content.Visuals = VisualsRepo.GetVisuals(content.ID);
            BBCode.ParseContent(content);

            viewModel.Project = content;

            return View(viewModel);
        }

        public ActionResult Reorder()
        {
            if (!Login.ForceHTTPSConnection(System.Web.HttpContext.Current, true)) return new EmptyResult();
            LogRepo.Log(System.Web.HttpContext.Current);
            var currentUser = Login.GetCurrentUser(System.Web.HttpContext.Current);
            if (currentUser.Permission < PCAuthLib.User.PermissionGroup.ADMIN) return RedirectToAction("Index", "Login");

            ProjectListViewModel viewModel = new ProjectListViewModel();

            List<Content> content =
                ContentRepo.GetAllContent(isAdmin: currentUser.Permission == PCAuthLib.User.PermissionGroup.ADMIN);

            if (content != null)
            {
                foreach (Content contentItem in content)
                {
                    BBCode.ParseContent(contentItem);

                    contentItem.HeaderImg = VisualsRepo.RandomVisual(contentItem.ID);
                }
            }

            viewModel.ContentList = content ?? new List<Content>();

            return View(viewModel);
        }

        [HttpPost]
        public string Reorder(string orderData)
        {
            if (!Login.ForceHTTPSConnection(System.Web.HttpContext.Current, true)) return "";
            var currentUser = Login.GetCurrentUser(System.Web.HttpContext.Current);
            if (currentUser.Permission < PCAuthLib.User.PermissionGroup.ADMIN) return "";


            //return orderData;
            if (String.IsNullOrEmpty(orderData)) return "";

            string[] newOrder = orderData.Split(',');
            return ContentRepo.UpdateOrder(newOrder).ToString();
        }

        public ActionResult Edit(int ID = 0)
        {
            if (!Login.ForceHTTPSConnection(System.Web.HttpContext.Current, true)) return new EmptyResult();
            LogRepo.Log(System.Web.HttpContext.Current);
            var currentUser = Login.GetCurrentUser(System.Web.HttpContext.Current);
            if (currentUser.Permission < PCAuthLib.User.PermissionGroup.ADMIN) return RedirectToAction("Index", "Login");

            ProjectViewModel viewModel = new ProjectViewModel();
            Content content = ContentRepo.GetContent(ID, currentUser.Permission == PCAuthLib.User.PermissionGroup.ADMIN);
            if (content != null)
            {
                content.Visuals = VisualsRepo.GetVisuals(content.ID);
                viewModel.Project = content;
            }
            return View(viewModel);
        }
        [HttpPost]
        public ActionResult Edit(ProjectViewModel viewModel)
        {
            if (!Login.ForceHTTPSConnection(System.Web.HttpContext.Current, true)) return new EmptyResult();
            LogRepo.Log(System.Web.HttpContext.Current);
            var currentUser = Login.GetCurrentUser(System.Web.HttpContext.Current);
            if (currentUser.Permission < PCAuthLib.User.PermissionGroup.ADMIN) return RedirectToAction("Index", "Login");

            if (viewModel.Project.ID > 0)
            {
                Content project = viewModel.Project;
                ContentRepo.UpdateContent(project);
            }
            else if (viewModel.Project.ID == 0)
            {
                if (ContentRepo.InsertContent(viewModel.Project))
                {
                    viewModel.Project = ContentRepo.GetLastContent();
                }
            }

            return RedirectToAction("Edit", new RouteValueDictionary() { { "ID", viewModel.Project.ID } });
        }

        [HttpPost]
        public ActionResult UploadMultiple(IEnumerable<HttpPostedFileBase> files, ProjectViewModel viewModel)
        {
            if (!Login.ForceHTTPSConnection(System.Web.HttpContext.Current, true)) return new EmptyResult();
            LogRepo.Log(System.Web.HttpContext.Current);
            var currentUser = Login.GetCurrentUser(System.Web.HttpContext.Current);
            if (currentUser.Permission < PCAuthLib.User.PermissionGroup.ADMIN) return RedirectToAction("Index", "Login");

            if (!Directory.Exists(Server.MapPath("/uploads")))
                Directory.CreateDirectory(Server.MapPath("/uploads"));
            foreach (var file in files)
            {
                if (file != null && file.ContentLength > 0)
                {
                    string filename = Guid.NewGuid() + Path.GetExtension(file.FileName);
                    string path = Path.Combine(Server.MapPath("/uploads"), filename);
                    file.SaveAs(path);
                    VisualsRepo.InsertVisual(viewModel.Project.ID, filename, Visual.ContentTypes.Photo);
                }
            }
            return RedirectToAction("Edit", new RouteValueDictionary() { { "ID", viewModel.Project.ID } });
        }

        [HttpPost]
        public ActionResult NewVideo(ProjectViewModel viewModel)
        {
            if (!Login.ForceHTTPSConnection(System.Web.HttpContext.Current, true)) return new EmptyResult();
            LogRepo.Log(System.Web.HttpContext.Current);
            var currentUser = Login.GetCurrentUser(System.Web.HttpContext.Current);
            if (currentUser.Permission < PCAuthLib.User.PermissionGroup.ADMIN) return RedirectToAction("Index", "Login");

            string extractedID = VideoExtract.ExtractYoutubeIdFromUri(new Uri(viewModel.PostVideo));
            if (extractedID != null)
                VisualsRepo.InsertVisual(viewModel.Project.ID, extractedID, Visual.ContentTypes.Video);
            else extractedID = VideoExtract.ExtractGfyCatIdFromUri(new Uri(viewModel.PostVideo));

            if (extractedID != null)
                VisualsRepo.InsertVisual(viewModel.Project.ID, extractedID, Visual.ContentTypes.GfyCat);

            return RedirectToAction("Edit", new RouteValueDictionary() { { "ID", viewModel.Project.ID } });
        }

        public ActionResult DeleteProject(int ID = 0)
        {
            if (!Login.ForceHTTPSConnection(System.Web.HttpContext.Current, true)) return new EmptyResult();
            LogRepo.Log(System.Web.HttpContext.Current);
            var currentUser = Login.GetCurrentUser(System.Web.HttpContext.Current);
            if (currentUser.Permission < PCAuthLib.User.PermissionGroup.ADMIN) return RedirectToAction("Index", "Login");

            Content content = ContentRepo.GetContent(ID);
            ProjectViewModel viewModel = new ProjectViewModel();
            viewModel.Project = content;
            return View(viewModel);
        }
        [HttpPost]
        public ActionResult DeleteProject(ProjectViewModel viewModel)
        {
            if (!Login.ForceHTTPSConnection(System.Web.HttpContext.Current, true)) return new EmptyResult();
            LogRepo.Log(System.Web.HttpContext.Current);
            var currentUser = Login.GetCurrentUser(System.Web.HttpContext.Current);
            if (currentUser.Permission < PCAuthLib.User.PermissionGroup.ADMIN) return RedirectToAction("Index", "Login");

            if (viewModel == null) return RedirectToAction("Index");
            Content content = ContentRepo.GetContent(viewModel.Project.ID, currentUser.Permission == PCAuthLib.User.PermissionGroup.ADMIN);
            if (content != null)
            {
                if (!string.IsNullOrEmpty(viewModel.DeleteConfirmationName) && viewModel.DeleteConfirmationName == content.Title)
                {
                    ContentRepo.DeleteContent(viewModel.Project.ID);
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.Error = "Entered name does not match Project name";
                    return View(viewModel);
                }
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult DeleteVisuals(ProjectViewModel viewModel)
        {

YouriPortfolio/YouriPortfolio/Views/Projects/DeleteProject.cshtml
@model YouriPortfolio.Models.ViewModels.ProjectViewModel
@{
    ViewBag.Title = "Delete";
}
<br/>
<div class="row">
    <div class="col-md-4 col-md-offset-4 ContentBlock text-center">
        <h2>Delete</h2>
        @using (Html.BeginForm("DeleteProject", "Projects", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(model => model.Project.ID)
            <p class="row">
                Are you sure you want to delete this page?<br />
                Type the name of the project to delete it.
            </p>
            <div class="row">
                @Html.EditorFor(model => model.DeleteConfirmationName)
                <input type="submit" value="Delete" class="btn btn-danger" />
            </div>
            if (!String.IsNullOrEmpty(ViewBag.Error))
            {
                <p>@ViewBag.Error</p>
            }

            <br />

        }
    </div>
</div>

YouriPortfolio/YouriPortfolio/Views/Projects/Edit.cshtml
@using YouriPortfolio.Models
@model YouriPortfolio.Models.ViewModels.ProjectViewModel
@{
    ViewBag.Title = "ContentEdit";
}
<head>
    <script src="~/Scripts/jquery.wysibb.min.js"></script>
    <link href="~/Content/wbbtheme.css" rel="stylesheet" />
</head>
<script>
    $(document).ready(function () {
        var wbbOpt = {
            buttons: "bold,italic,underline,fontcolor,|,img,link,code,fa,|,h1,h2,h3,h4",
            allButtons: {
                h1: {
                    title: 'Insert h1',
                    buttonText: 'h1',
                    hotkey: "ctrl+shift+1", //Add hotkey
                    transform: {
                        '<h1>{SELTEXT}</h1>': '[h1]{SELTEXT}[/h1]'
                    }
                },
                h2: {
                    title: 'Insert h2',
                    buttonText: 'h2',
                    hotkey: "ctrl+shift+2", //Add hotkey
                    transform: {
                        '<h2>{SELTEXT}</h2>': '[h2]{SELTEXT}[/h2]'
                    }
                },
                h3: {
                    title: 'Insert h3',
                    buttonText: 'h3',
                    hotkey: "ctrl+shift+3", //Add hotkey
                    transform: {
                        '<h3>{SELTEXT}</h3>': '[h3]{SELTEXT}[/h3]'
                    }
                },
                h4: {
                    title: 'Insert h4',
                    buttonText: 'h4',
                    hotkey: "ctrl+shift+4", //Add hotkey
                    transform: {
                        '<h4>{SELTEXT}</h4>': '[h4]{SELTEXT}[/h4]'
                    }
                }
            }
        }
        $("#Project_ContentText").wysibb(wbbOpt);
        $("#Project_ShortContent").wysibb(wbbOpt);
    });
</script>

<script type="text/javascript">
    $(function () {
        if (window.FileReader != null) {
            $('#single').hide();
            $('.single').prop('disabled', true);
        } else {
            $('#multiple').hide();
            $('.multiple').prop('disabled', true);
        }
    });
</script>

<br />
<div class="row">
    <div class="ContentBlock">
        <div class="row">
            <h2>Project Edit Page</h2>

            @using (Html.BeginForm("Edit", "Projects", FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                @Html.HiddenFor(model => model.Project.ID)
                @Html.HiddenFor(model => model.Project.Priority)


                <div class="row">
                    <div class="text-left col-xs-6">
                        <span style="padding-left: 15px">Public</span>
                        @Html.EditorFor(model => model.Project.Shown)
                    </div>
                    <div class="text-right col-xs-6">
                        @Html.ActionLink("To Project", "Get", new { ID = Model.Project.ID }, new { @class = "btn btn-primary" })
                        @Html.ActionLink("Delete", "DeleteProject", new { ID = Model.Project.ID }, new { @class = "btn btn-danger" })
                    </div>
                </div>
                <div class="col-md-8">
                    <h3>Project Content</h3>

                    <div class="row">
                        <div class="col-sm-4">
                            <h4>Title</h4>
                            @Html.EditorFor(model => model.Project.Title, new { htmlAttributes = new { @style = "width:100%;" } })
                        </div>
                        <div class="col-sm-4 col-sm-offset-4">
                            <h4>Date</h4>
                            @Html.EditorFor(model => model.Project.Date, new { htmlAttributes = new { @style = "width:100%;" } })
                        </div>
                    </div>
                    <br/>
                    <h4>Short Description</h4>
                    @Html.TextAreaFor(model => model.Project.ShortContent, new { @style = "min-height:100px" })
                    <br/>
                    <h4>Full Description</h4>
                    @Html.TextAreaFor(model => model.Project.ContentText, new { @style = "min-height:200px" })
                    <br />
                    <input type="submit" value="Save" class="btn btn-primary" />


                </div>
            }
            <div class="col-md-4">
                @if (Model.Project.ID > 0)
                {
                    <h3>Visual content management</h3>
                                <div class="row">
                                    <h4>Upload Visuals</h4>
                                    @using (Html.BeginForm("UploadMultiple", "Projects", FormMethod.Post, new { enctype = "multipart/form-data" }))
                                    {
                                        @Html.AntiForgeryToken()
                                        @Html.HiddenFor(model => model.Project.ID)
                                        <div id="multiple">
                                            <input type="file" class="multiple" name="files" multiple />
                                        </div>
                                        <div id="single">
                                            <input type="file" class="single" name="files" /><br />
                                            <input type="file" class="single" name="files" /><br />
                                            <input type="file" class="single" name="files" /><br />
                                        </div>
                                        <br />
                                        <button class="btn btn-success">Upload</button>
                                    }
                                    <br />
                                    <br />
                                    <h4>New Videos</h4>
                                    @using (Html.BeginForm("NewVideo", "Projects", FormMethod.Post))
                                    {
                                        @Html.AntiForgeryToken()
                                        @Html.HiddenFor(model => model.Project.ID)

                                        @Html.TextBoxFor(model => model.PostVideo)

                                        <br />
                                        <button class="btn btn-success">Upload</button>
                                    }

                                </div>

                                <br />
                                <div class="row">

                                    @using (Html.BeginForm("DeleteVisuals", "Projects", FormMethod.Post, new { enctype = "multipart/form-data" }))
                                    {
                                        @Html.AntiForgeryToken()
                                        @Html.HiddenFor(model => model.Project.ID)
                                        <h4>Delete Visuals</h4>
                                        <div class="row">
                                            @for (int i = 0; i < Model.Project.Visuals.Count; i++)
                                            {
                                                <div class="col-xs-6 ">
                                                    <div class=" text-center VisualBlock">

                                                        @Html.HiddenFor(model => model.Project.Visuals[i].ID)
                                                        @Html.HiddenFor(model => model.Project.Visuals[i].Location)
                                                        @Html.CheckBoxFor(model => model.Project.Visuals[i].Selected)
                                                        <br />
                                                        @if (Model.Project.Visuals[i].ContentType == Visual.ContentTypes.Photo)
                                                        {
                                                            <img src="/uploads/@Model.Project.Visuals[i].Location" />
                                                        }
                                                        else if(Model.Project.Visuals[i].ContentType == Visual.ContentTypes.Video)
                                                        {
                                                            <img src="//img.youtube.com/vi/@Model.Project.Visuals[i].Location/default.jpg" />
                                                        }
                                                        else if (Model.Project.Visuals[i].ContentType == Visual.ContentTypes.GfyCat)
                                                        {
                                                            <img src="https://thumbs.gfycat.com/@(Model.Project.Visuals[i].Location)-size_restricted.gif"/>
                                                        }
                                                    </div>
                                                </div>
                                            }
                                        </div>
                                        <br />
                                        <button class="btn btn-danger">Delete</button>
                                    }
                                </div>
                }
            </div>
        </div>
    </div>
</div>

YouriPortfolio/YouriPortfolio/Views/Projects/Get.cshtml
@using PCAuthLib
@using YouriPortfolio.Models
@model YouriPortfolio.Models.ViewModels.ProjectViewModel
@{
    ViewBag.Title = "Project";
    var currentUser = Login.GetCurrentUser(HttpContext.Current);
}

@if (Model.Project.Visuals != null && Model.Project.Visuals.Count > 0)
{
    <link href="~/Content/camera.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/cameraSettingCss.css" rel="stylesheet" type="text/css" />

    <script type="text/javascript" src="~/scripts/jquery.mobile.customized.min.js"></script>
    <script type="text/javascript" src="~/scripts/jquery.easing.1.3.js"></script>
    <script type="text/javascript" src="~/scripts/camera.js"></script>


    <script>
        jQuery(function () {

            jQuery('#camera_wrap_3').camera({
                height: '56%',
                pagination: false,
                thumbnails: true,
                imagePath: '/images/',
                fx: 'simpleFade',
                time: 12000
            });

        });
    </script>


    <br />

}<br /><br />
@if (currentUser.Permission >= PCAuthLib.User.PermissionGroup.ADMIN)
{
    <div class="row text-right">
        @Html.ActionLink("Edit", "Edit", new { ID = Model.Project.ID }, new { @class = "btn btn-primary" })
    </div>
    <br />
}
@if (Model.Project.Visuals != null && Model.Project.Visuals.Count > 0)
{
    <div class="outer_container">
        <div class="fluid_container">
            <div class="camera_wrap camera_emboss" id="camera_wrap_3">
                @foreach (Visual visual in Model.Project.Visuals)
                {
                    if (visual.ContentType == Visual.ContentTypes.Photo)
                    {
                        <div data-thumb="/uploads/@visual.Location" data-src="/uploads/@visual.Location">
                            <div style="position: absolute; top: 5%; left: 5%; padding: 5px; width: 25%" class="fadeIn camera_effected"></div>
                        </div>
                    }
                    else if (visual.ContentType == Visual.ContentTypes.Video)
                    {
                        <div data-thumb="//img.youtube.com/vi/@visual.Location/0.jpg" data-src="//img.youtube.com/vi/@visual.Location/default.jpg">
                            <iframe width="100%" height="100%" src="https://www.youtube.com/embed/@visual.Location" frameborder="0" allowfullscreen></iframe>
                        </div>
                    }
                    else if (visual.ContentType == Visual.ContentTypes.GfyCat)
                    {
                        <div data-thumb="https://thumbs.gfycat.com/@(visual.Location)-size_restricted.gif" data-src="/images/blank.gif">
                            <iframe src='https://gfycat.com/ifr/@visual.Location' frameborder='0' scrolling='no' width='100%' height='100%' style='position:absolute;top:0;left:0;' allowfullscreen></iframe>
                        </div>
                        
                    }
                }
            </div><!-- #camera_wrap_3 -->
        </div><!-- .fluid_container -->
    </div>
    <div style="clear: both; display: block; height: 30px"></div>
}
<div class="col-md-12 LGProjectBlock">
    <div class="ProjectTextBlock">
        <p class="footerText">@Model.Project.Date</p>
        <h2>@Html.Raw(Model.Project.Title)</h2>
        <h4>@Html.Raw(Model.Project.ShortContent)</h4>

        <br/>

        <p>@Html.Raw(Model.Project.ContentText)</p>
    </div>

</div>

YouriPortfolio/YouriPortfolio/Views/Projects/Index.cshtml
@using PCAuthLib
@using YouriPortfolio.Models
@model YouriPortfolio.Models.ViewModels.ProjectListViewModel
@{
    ViewBag.Title = "Projects";
    var currentUser = Login.GetCurrentUser(HttpContext.Current);
}

<br />
<div class="row">
    <h2>Projects</h2>
    @if (currentUser.Permission >= PCAuthLib.User.PermissionGroup.ADMIN)
    {
        <div class="row text-right">
            @Html.ActionLink("Reorder", "Reorder", new { }, new { @class = "btn btn-primary" })
            @Html.ActionLink("New", "Edit", new { ID = 0 }, new { @class = "btn btn-success" })
        </div>
    }
    <script>
        function Masonize() {
            $('.grid').masonry({
                itemSelector: '.grid-item', // use a separate class for itemSelector, other than .col-
                columnWidth: '.grid-sizer',
                percentPosition: true
            });
        }

        $(document).ready(function () {
            Masonize();
        });
        $(window).load(function () {
            Masonize();
        });
    </script>

    <div class="container-fluid">
        <!-- add extra container element for Masonry -->
        <div class="grid">
            <!-- add sizing element for columnWidth -->
            <div class="grid-sizer col-lg-3 col-sm-4 col-xs-6 col-xxs-12"></div>
            @foreach (Content content in Model.ContentList)
            {
                <div class="grid-item col-lg-3 col-sm-4 col-xs-6 col-xxs-12">
                    <div class="grid-item-content ZoomBlock">
                        <div class="ProjectBlock noLink" style="@(content.Shown?"": "background-color:lightgray")" onclick="window.location = '/Projects/Get/@content.ID';">
                            <div class="ProjectImage">
                                @if (content.HeaderImg != null && content.HeaderImg.Location != null && content.HeaderImg.Location.Length > 1)
                                {
                                    if (content.HeaderImg.ContentType == Visual.ContentTypes.Photo)
                                    {
                                        <img src="/uploads/@content.HeaderImg.Location" alt="Project Visual" />
                                    }
                                    else if(content.HeaderImg.ContentType == Visual.ContentTypes.Video)
                                    {
                                        <img src="//img.youtube.com/vi/@content.HeaderImg.Location/default.jpg" alt="Project Visual" />
                                    }
                                    else if (content.HeaderImg.ContentType == Visual.ContentTypes.GfyCat)
                                    {
                                        <img src="https://thumbs.gfycat.com/@(content.HeaderImg.Location)-size_restricted.gif"/>
                                    }
                                }
                            </div>
                            <div class="ProjectTextBlock">
                                <p class="footerText">
                                    @content.Date
                                </p>
                                <h2 class="ProjectTitle">
                                    @Html.Raw(content.Title)
                                </h2>
                                <p>@Html.Raw(content.ShortContent)</p>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>

</div>

YouriPortfolio/YouriPortfolio/Views/Projects/Reorder.cshtml
@using PCAuthLib
@using YouriPortfolio.Models
@model YouriPortfolio.Models.ViewModels.ProjectListViewModel
@{
    ViewBag.Title = "Projects";
    var currentUser = Login.GetCurrentUser(HttpContext.Current);
}

<br />
<div class="row">
    <h2>Projects</h2>
    @if (currentUser.Permission >= PCAuthLib.User.PermissionGroup.ADMIN)
    {
        <div class="row text-right">
            @Html.ActionLink("New", "Edit", new { ID = 0 }, new { @class = "btn btn-primary" })
        </div>
    }
    <script>
        $(document).ready(function () {
            $('.grid').masonry({
                itemSelector: '.grid-item', // use a separate class for itemSelector, other than .col-
                columnWidth: '.grid-sizer',
                percentPosition: true
            });
        });
        $(document).ready(function () {
            $("#sortable").sortable({
                update: function (event, ui) {
                    var sortableData = $("#sortable").sortable('toArray').join(",");
                    $.ajax({
                        data: {
                            "orderData": sortableData
                        },
                        type: 'POST',
                        url: '/Projects/Reorder'
                    });
                }
            });
            $("#sortable").disableSelection();
        });
    </script>



    <ul id="sortable">
        @foreach (Content content in Model.ContentList)
        {
            <li class="ui-state-default" id="@content.ID">
                <span class="ui-icon ui-icon-arrowthick-2-n-s"></span>
                @Html.Raw(content.Title)
            </li>
        }
    </ul>

</div>