YouriPortfolio/YouriPortfolio/Controllers/CVController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using PCAuthLib;
using PermacallWebApp.Repos;
using YouriPortfolio.Logic;
using YouriPortfolio.Models;
using YouriPortfolio.Repos;

namespace YouriPortfolio.Controllers
{
    public class CVController : Controller
    {
        // GET: CV
        public ActionResult Index()
        {
            if (!Login.ForceHTTPSConnection(System.Web.HttpContext.Current, true)) return new EmptyResult();
            LogRepo.Log(System.Web.HttpContext.Current);


            CVViewModel viewModel = ContentRepo.GetCV();
            if(viewModel == null) return View(new CVViewModel());

            viewModel.ExperienceText = BBCode.ParseBBCode(viewModel.ExperienceText);
            viewModel.AboutMeText = BBCode.ParseBBCode(viewModel.AboutMeText);
            viewModel.EducationText = BBCode.ParseBBCode(viewModel.EducationText);
            return View(viewModel);
        }

        public ActionResult Edit()
        {
            if (!Login.ForceHTTPSConnection(System.Web.HttpContext.Current, true)) return new EmptyResult();
            LogRepo.Log(System.Web.HttpContext.Current);
            var currentUser = Login.GetCurrentUser(System.Web.HttpContext.Current);
            if (currentUser.Permission < PCAuthLib.User.PermissionGroup.ADMIN) return RedirectToAction("Index", "Login");

            CVViewModel viewModel = ContentRepo.GetCV();
            if (viewModel == null) viewModel = new CVViewModel();

            if (viewModel.SkillKeyValues.Count > 0)
            {
                viewModel.SkillKeyValuesJson = JsonConvert.SerializeObject(viewModel.SkillKeyValues, Formatting.Indented);
            }
            else
            {
                Dictionary<string,int> toJson = new Dictionary<string, int>();
                toJson.Add("C#", 0);
                toJson.Add("ASP.net", 0);
                viewModel.SkillKeyValuesJson = JsonConvert.SerializeObject(toJson, Formatting.Indented);
            }
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Edit(CVViewModel viewModel)
        {
            if (!Login.ForceHTTPSConnection(System.Web.HttpContext.Current, true)) return new EmptyResult();
            LogRepo.Log(System.Web.HttpContext.Current);
            var currentUser = Login.GetCurrentUser(System.Web.HttpContext.Current);
            if (currentUser.Permission < PCAuthLib.User.PermissionGroup.ADMIN) return RedirectToAction("Index", "Login");


            if (viewModel != null)
            {
                viewModel.SkillKeyValues =
                    JsonConvert.DeserializeObject<Dictionary<string, int>>(viewModel.SkillKeyValuesJson);
                ContentRepo.UpdateCV(JsonConvert.SerializeObject(viewModel));
            }
            return RedirectToAction("Index");
        }
    }
}

YouriPortfolio/YouriPortfolio/Views/Shared/_Layout.cshtml
@using PCAuthLib
@using YouriPortfolio.Models
@{
    User currentUser = Login.GetCurrentUser(HttpContext.Current);
}


<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Youri Schuurmans</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/jquery-ui.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" type="text/css" href="~/Content/cookieBar.min.css">

    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery-ui.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/main.js"></script>
    <script src="~/Scripts/masonry.pkgd.min.js"></script>
    <script src="~/Scripts/jquery.cookieBar.min.js"></script>
    <script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js"></script>


    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">

    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32">
    <link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16">
    <link rel="manifest" href="/manifest.json">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="theme-color" content="#ffffff">


    <link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.css" />
    <script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.js"></script>
    <script>    window.addEventListener("load", function () { window.cookieconsent.initialise({ "palette": { "popup": { "background": "#edeff5", "text": "#838391" }, "button": { "background": "#4b81e8" } }, "position": "top", "static": true, "content": { "message": "This website uses cookies to ensure you get the best experience on our website. By continuing to browse the site you are agreeing to our use of cookies.", "dismiss": "Dismiss" } }) });</script>
</head>
<body>
<div id="navbarddiv" class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>

            </button>
            @Html.ActionLink("Youri Schuurmans", "Index", "CV", new {area = ""}, new {@class = "navbar-brand"})
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">

                @Html.LiActionLink("Curriculum Vitae", "Index", "CV")
                @Html.LiActionLink("Projects", "Index", "Projects")

                @*<li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                Projects
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                @Html.LiActionLink("DotNet C# / ASP.NET MVC", "", "")
                                @Html.LiActionLink("Game Design", "", "")
                                @Html.LiActionLink("HTML&CSS", "", "")
                            </ul>
                        </li>*@
                @*<li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                <i class="fa fa-user" aria-hidden="false"></i>
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                @if (currentUser.ID > 0)
                                {
                                    <li class="text-center">@currentUser.Username</li>
                                    @Html.LiActionLink("Logout", "Logout", "Login")
                                }
                                else
                                {
                                    @Html.LiActionLink("Login", "Index", "Login")
                                }
                            </ul>
                        </li>*@

            </ul>

        </div>
    </div>
</div>


@*@Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@


<div class="container body-content">
    @RenderBody()
    <br/>
    <footer class="text-right pageFooter">
        <p>
            &copy; @DateTime.Now.Year - Youri Schuurmans<br/>
            v 1.2.3
        </p>
    </footer>
</div>


</body>
</html>